/**
 *
 *  Jobs.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Jobs.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::calendar_db;

const std::string Jobs::Cols::_id = "\"id\"";
const std::string Jobs::Cols::_impact_id = "\"impact_id\"";
const std::string Jobs::Cols::_time_stamp = "\"time_stamp\"";
const std::string Jobs::Cols::_location_id = "\"location_id\"";
const std::string Jobs::Cols::_additional_load = "\"additional_load\"";
const std::string Jobs::Cols::_total_load = "\"total_load\"";
const std::string Jobs::primaryKeyName = "id";
const bool Jobs::hasPrimaryKey = true;
const std::string Jobs::tableName = "\"jobs\"";

const std::vector<typename Jobs::MetaData> Jobs::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"impact_id","int32_t","integer",4,0,0,1},
{"time_stamp","::trantor::Date","timestamp with time zone",0,0,0,1},
{"location_id","std::string","text",0,0,0,0},
{"additional_load","double","double precision",8,0,0,0},
{"total_load","double","double precision",8,0,0,0}
};
const std::string &Jobs::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Jobs::Jobs(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["impact_id"].isNull())
        {
            impactId_=std::make_shared<int32_t>(r["impact_id"].as<int32_t>());
        }
        if(!r["time_stamp"].isNull())
        {
            auto timeStr = r["time_stamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["location_id"].isNull())
        {
            locationId_=std::make_shared<std::string>(r["location_id"].as<std::string>());
        }
        if(!r["additional_load"].isNull())
        {
            additionalLoad_=std::make_shared<double>(r["additional_load"].as<double>());
        }
        if(!r["total_load"].isNull())
        {
            totalLoad_=std::make_shared<double>(r["total_load"].as<double>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            impactId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            locationId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            additionalLoad_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            totalLoad_=std::make_shared<double>(r[index].as<double>());
        }
    }

}

Jobs::Jobs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            impactId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            totalLoad_=std::make_shared<double>(pJson[pMasqueradingVector[5]].asDouble());
        }
    }
}

Jobs::Jobs(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("impact_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["impact_id"].isNull())
        {
            impactId_=std::make_shared<int32_t>((int32_t)pJson["impact_id"].asInt64());
        }
    }
    if(pJson.isMember("time_stamp"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["time_stamp"].isNull())
        {
            auto timeStr = pJson["time_stamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("location_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["location_id"].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson["location_id"].asString());
        }
    }
    if(pJson.isMember("additional_load"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["additional_load"].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson["additional_load"].asDouble());
        }
    }
    if(pJson.isMember("total_load"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["total_load"].isNull())
        {
            totalLoad_=std::make_shared<double>(pJson["total_load"].asDouble());
        }
    }
}

void Jobs::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            impactId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            totalLoad_=std::make_shared<double>(pJson[pMasqueradingVector[5]].asDouble());
        }
    }
}

void Jobs::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("impact_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["impact_id"].isNull())
        {
            impactId_=std::make_shared<int32_t>((int32_t)pJson["impact_id"].asInt64());
        }
    }
    if(pJson.isMember("time_stamp"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["time_stamp"].isNull())
        {
            auto timeStr = pJson["time_stamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("location_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["location_id"].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson["location_id"].asString());
        }
    }
    if(pJson.isMember("additional_load"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["additional_load"].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson["additional_load"].asDouble());
        }
    }
    if(pJson.isMember("total_load"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["total_load"].isNull())
        {
            totalLoad_=std::make_shared<double>(pJson["total_load"].asDouble());
        }
    }
}

const int32_t &Jobs::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Jobs::getId() const noexcept
{
    return id_;
}
void Jobs::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Jobs::PrimaryKeyType & Jobs::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Jobs::getValueOfImpactId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(impactId_)
        return *impactId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Jobs::getImpactId() const noexcept
{
    return impactId_;
}
void Jobs::setImpactId(const int32_t &pImpactId) noexcept
{
    impactId_ = std::make_shared<int32_t>(pImpactId);
    dirtyFlag_[1] = true;
}

const ::trantor::Date &Jobs::getValueOfTimeStamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(timeStamp_)
        return *timeStamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Jobs::getTimeStamp() const noexcept
{
    return timeStamp_;
}
void Jobs::setTimeStamp(const ::trantor::Date &pTimeStamp) noexcept
{
    timeStamp_ = std::make_shared<::trantor::Date>(pTimeStamp);
    dirtyFlag_[2] = true;
}

const std::string &Jobs::getValueOfLocationId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(locationId_)
        return *locationId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Jobs::getLocationId() const noexcept
{
    return locationId_;
}
void Jobs::setLocationId(const std::string &pLocationId) noexcept
{
    locationId_ = std::make_shared<std::string>(pLocationId);
    dirtyFlag_[3] = true;
}
void Jobs::setLocationId(std::string &&pLocationId) noexcept
{
    locationId_ = std::make_shared<std::string>(std::move(pLocationId));
    dirtyFlag_[3] = true;
}
void Jobs::setLocationIdToNull() noexcept
{
    locationId_.reset();
    dirtyFlag_[3] = true;
}

const double &Jobs::getValueOfAdditionalLoad() const noexcept
{
    static const double defaultValue = double();
    if(additionalLoad_)
        return *additionalLoad_;
    return defaultValue;
}
const std::shared_ptr<double> &Jobs::getAdditionalLoad() const noexcept
{
    return additionalLoad_;
}
void Jobs::setAdditionalLoad(const double &pAdditionalLoad) noexcept
{
    additionalLoad_ = std::make_shared<double>(pAdditionalLoad);
    dirtyFlag_[4] = true;
}
void Jobs::setAdditionalLoadToNull() noexcept
{
    additionalLoad_.reset();
    dirtyFlag_[4] = true;
}

const double &Jobs::getValueOfTotalLoad() const noexcept
{
    static const double defaultValue = double();
    if(totalLoad_)
        return *totalLoad_;
    return defaultValue;
}
const std::shared_ptr<double> &Jobs::getTotalLoad() const noexcept
{
    return totalLoad_;
}
void Jobs::setTotalLoad(const double &pTotalLoad) noexcept
{
    totalLoad_ = std::make_shared<double>(pTotalLoad);
    dirtyFlag_[5] = true;
}
void Jobs::setTotalLoadToNull() noexcept
{
    totalLoad_.reset();
    dirtyFlag_[5] = true;
}

void Jobs::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Jobs::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "impact_id",
        "time_stamp",
        "location_id",
        "additional_load",
        "total_load"
    };
    return inCols;
}

void Jobs::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getImpactId())
        {
            binder << getValueOfImpactId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTimeStamp())
        {
            binder << getValueOfTimeStamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLocationId())
        {
            binder << getValueOfLocationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAdditionalLoad())
        {
            binder << getValueOfAdditionalLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTotalLoad())
        {
            binder << getValueOfTotalLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Jobs::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Jobs::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getImpactId())
        {
            binder << getValueOfImpactId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTimeStamp())
        {
            binder << getValueOfTimeStamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLocationId())
        {
            binder << getValueOfLocationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAdditionalLoad())
        {
            binder << getValueOfAdditionalLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTotalLoad())
        {
            binder << getValueOfTotalLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Jobs::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getImpactId())
    {
        ret["impact_id"]=getValueOfImpactId();
    }
    else
    {
        ret["impact_id"]=Json::Value();
    }
    if(getTimeStamp())
    {
        ret["time_stamp"]=getTimeStamp()->toDbStringLocal();
    }
    else
    {
        ret["time_stamp"]=Json::Value();
    }
    if(getLocationId())
    {
        ret["location_id"]=getValueOfLocationId();
    }
    else
    {
        ret["location_id"]=Json::Value();
    }
    if(getAdditionalLoad())
    {
        ret["additional_load"]=getValueOfAdditionalLoad();
    }
    else
    {
        ret["additional_load"]=Json::Value();
    }
    if(getTotalLoad())
    {
        ret["total_load"]=getValueOfTotalLoad();
    }
    else
    {
        ret["total_load"]=Json::Value();
    }
    return ret;
}

Json::Value Jobs::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getImpactId())
            {
                ret[pMasqueradingVector[1]]=getValueOfImpactId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTimeStamp())
            {
                ret[pMasqueradingVector[2]]=getTimeStamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLocationId())
            {
                ret[pMasqueradingVector[3]]=getValueOfLocationId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getAdditionalLoad())
            {
                ret[pMasqueradingVector[4]]=getValueOfAdditionalLoad();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTotalLoad())
            {
                ret[pMasqueradingVector[5]]=getValueOfTotalLoad();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getImpactId())
    {
        ret["impact_id"]=getValueOfImpactId();
    }
    else
    {
        ret["impact_id"]=Json::Value();
    }
    if(getTimeStamp())
    {
        ret["time_stamp"]=getTimeStamp()->toDbStringLocal();
    }
    else
    {
        ret["time_stamp"]=Json::Value();
    }
    if(getLocationId())
    {
        ret["location_id"]=getValueOfLocationId();
    }
    else
    {
        ret["location_id"]=Json::Value();
    }
    if(getAdditionalLoad())
    {
        ret["additional_load"]=getValueOfAdditionalLoad();
    }
    else
    {
        ret["additional_load"]=Json::Value();
    }
    if(getTotalLoad())
    {
        ret["total_load"]=getValueOfTotalLoad();
    }
    else
    {
        ret["total_load"]=Json::Value();
    }
    return ret;
}

bool Jobs::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("impact_id"))
    {
        if(!validJsonOfField(1, "impact_id", pJson["impact_id"], err, true))
            return false;
    }
    else
    {
        err="The impact_id column cannot be null";
        return false;
    }
    if(pJson.isMember("time_stamp"))
    {
        if(!validJsonOfField(2, "time_stamp", pJson["time_stamp"], err, true))
            return false;
    }
    else
    {
        err="The time_stamp column cannot be null";
        return false;
    }
    if(pJson.isMember("location_id"))
    {
        if(!validJsonOfField(3, "location_id", pJson["location_id"], err, true))
            return false;
    }
    if(pJson.isMember("additional_load"))
    {
        if(!validJsonOfField(4, "additional_load", pJson["additional_load"], err, true))
            return false;
    }
    if(pJson.isMember("total_load"))
    {
        if(!validJsonOfField(5, "total_load", pJson["total_load"], err, true))
            return false;
    }
    return true;
}
bool Jobs::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Jobs::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("impact_id"))
    {
        if(!validJsonOfField(1, "impact_id", pJson["impact_id"], err, false))
            return false;
    }
    if(pJson.isMember("time_stamp"))
    {
        if(!validJsonOfField(2, "time_stamp", pJson["time_stamp"], err, false))
            return false;
    }
    if(pJson.isMember("location_id"))
    {
        if(!validJsonOfField(3, "location_id", pJson["location_id"], err, false))
            return false;
    }
    if(pJson.isMember("additional_load"))
    {
        if(!validJsonOfField(4, "additional_load", pJson["additional_load"], err, false))
            return false;
    }
    if(pJson.isMember("total_load"))
    {
        if(!validJsonOfField(5, "total_load", pJson["total_load"], err, false))
            return false;
    }
    return true;
}
bool Jobs::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector,
                                            std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Jobs::validJsonOfField(size_t index,
                            const std::string &fieldName,
                            const Json::Value &pJson,
                            std::string &err,
                            bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
