/**
 *
 *  TrivialJobs.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TrivialJobs.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::calendar_db;

const std::string TrivialJobs::Cols::_id = "\"id\"";
const std::string TrivialJobs::Cols::_trivial_impact_id = "\"trivial_impact_id\"";
const std::string TrivialJobs::Cols::_time_stamp = "\"time_stamp\"";
const std::string TrivialJobs::Cols::_location_id = "\"location_id\"";
const std::string TrivialJobs::Cols::_additional_load = "\"additional_load\"";
const std::string TrivialJobs::primaryKeyName = "id";
const bool TrivialJobs::hasPrimaryKey = true;
const std::string TrivialJobs::tableName = "\"trivial_jobs\"";

const std::vector<typename TrivialJobs::MetaData> TrivialJobs::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"trivial_impact_id","int32_t","integer",4,0,0,1},
{"time_stamp","::trantor::Date","timestamp with time zone",0,0,0,1},
{"location_id","std::string","text",0,0,0,0},
{"additional_load","double","double precision",8,0,0,0}
};
const std::string &TrivialJobs::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TrivialJobs::TrivialJobs(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["trivial_impact_id"].isNull())
        {
            trivialImpactId_=std::make_shared<int32_t>(r["trivial_impact_id"].as<int32_t>());
        }
        if(!r["time_stamp"].isNull())
        {
            auto timeStr = r["time_stamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["location_id"].isNull())
        {
            locationId_=std::make_shared<std::string>(r["location_id"].as<std::string>());
        }
        if(!r["additional_load"].isNull())
        {
            additionalLoad_=std::make_shared<double>(r["additional_load"].as<double>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            trivialImpactId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            locationId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            additionalLoad_=std::make_shared<double>(r[index].as<double>());
        }
    }

}

TrivialJobs::TrivialJobs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trivialImpactId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
}

TrivialJobs::TrivialJobs(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("trivial_impact_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["trivial_impact_id"].isNull())
        {
            trivialImpactId_=std::make_shared<int32_t>((int32_t)pJson["trivial_impact_id"].asInt64());
        }
    }
    if(pJson.isMember("time_stamp"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["time_stamp"].isNull())
        {
            auto timeStr = pJson["time_stamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("location_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["location_id"].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson["location_id"].asString());
        }
    }
    if(pJson.isMember("additional_load"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["additional_load"].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson["additional_load"].asDouble());
        }
    }
}

void TrivialJobs::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trivialImpactId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
}

void TrivialJobs::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("trivial_impact_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["trivial_impact_id"].isNull())
        {
            trivialImpactId_=std::make_shared<int32_t>((int32_t)pJson["trivial_impact_id"].asInt64());
        }
    }
    if(pJson.isMember("time_stamp"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["time_stamp"].isNull())
        {
            auto timeStr = pJson["time_stamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timeStamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("location_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["location_id"].isNull())
        {
            locationId_=std::make_shared<std::string>(pJson["location_id"].asString());
        }
    }
    if(pJson.isMember("additional_load"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["additional_load"].isNull())
        {
            additionalLoad_=std::make_shared<double>(pJson["additional_load"].asDouble());
        }
    }
}

const int32_t &TrivialJobs::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TrivialJobs::getId() const noexcept
{
    return id_;
}
void TrivialJobs::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename TrivialJobs::PrimaryKeyType & TrivialJobs::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &TrivialJobs::getValueOfTrivialImpactId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(trivialImpactId_)
        return *trivialImpactId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TrivialJobs::getTrivialImpactId() const noexcept
{
    return trivialImpactId_;
}
void TrivialJobs::setTrivialImpactId(const int32_t &pTrivialImpactId) noexcept
{
    trivialImpactId_ = std::make_shared<int32_t>(pTrivialImpactId);
    dirtyFlag_[1] = true;
}

const ::trantor::Date &TrivialJobs::getValueOfTimeStamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(timeStamp_)
        return *timeStamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TrivialJobs::getTimeStamp() const noexcept
{
    return timeStamp_;
}
void TrivialJobs::setTimeStamp(const ::trantor::Date &pTimeStamp) noexcept
{
    timeStamp_ = std::make_shared<::trantor::Date>(pTimeStamp);
    dirtyFlag_[2] = true;
}

const std::string &TrivialJobs::getValueOfLocationId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(locationId_)
        return *locationId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TrivialJobs::getLocationId() const noexcept
{
    return locationId_;
}
void TrivialJobs::setLocationId(const std::string &pLocationId) noexcept
{
    locationId_ = std::make_shared<std::string>(pLocationId);
    dirtyFlag_[3] = true;
}
void TrivialJobs::setLocationId(std::string &&pLocationId) noexcept
{
    locationId_ = std::make_shared<std::string>(std::move(pLocationId));
    dirtyFlag_[3] = true;
}
void TrivialJobs::setLocationIdToNull() noexcept
{
    locationId_.reset();
    dirtyFlag_[3] = true;
}

const double &TrivialJobs::getValueOfAdditionalLoad() const noexcept
{
    static const double defaultValue = double();
    if(additionalLoad_)
        return *additionalLoad_;
    return defaultValue;
}
const std::shared_ptr<double> &TrivialJobs::getAdditionalLoad() const noexcept
{
    return additionalLoad_;
}
void TrivialJobs::setAdditionalLoad(const double &pAdditionalLoad) noexcept
{
    additionalLoad_ = std::make_shared<double>(pAdditionalLoad);
    dirtyFlag_[4] = true;
}
void TrivialJobs::setAdditionalLoadToNull() noexcept
{
    additionalLoad_.reset();
    dirtyFlag_[4] = true;
}

void TrivialJobs::updateId(const uint64_t id)
{
}

const std::vector<std::string> &TrivialJobs::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "trivial_impact_id",
        "time_stamp",
        "location_id",
        "additional_load"
    };
    return inCols;
}

void TrivialJobs::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrivialImpactId())
        {
            binder << getValueOfTrivialImpactId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTimeStamp())
        {
            binder << getValueOfTimeStamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLocationId())
        {
            binder << getValueOfLocationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAdditionalLoad())
        {
            binder << getValueOfAdditionalLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TrivialJobs::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void TrivialJobs::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrivialImpactId())
        {
            binder << getValueOfTrivialImpactId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTimeStamp())
        {
            binder << getValueOfTimeStamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLocationId())
        {
            binder << getValueOfLocationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAdditionalLoad())
        {
            binder << getValueOfAdditionalLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TrivialJobs::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrivialImpactId())
    {
        ret["trivial_impact_id"]=getValueOfTrivialImpactId();
    }
    else
    {
        ret["trivial_impact_id"]=Json::Value();
    }
    if(getTimeStamp())
    {
        ret["time_stamp"]=getTimeStamp()->toDbStringLocal();
    }
    else
    {
        ret["time_stamp"]=Json::Value();
    }
    if(getLocationId())
    {
        ret["location_id"]=getValueOfLocationId();
    }
    else
    {
        ret["location_id"]=Json::Value();
    }
    if(getAdditionalLoad())
    {
        ret["additional_load"]=getValueOfAdditionalLoad();
    }
    else
    {
        ret["additional_load"]=Json::Value();
    }
    return ret;
}

Json::Value TrivialJobs::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTrivialImpactId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTrivialImpactId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTimeStamp())
            {
                ret[pMasqueradingVector[2]]=getTimeStamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLocationId())
            {
                ret[pMasqueradingVector[3]]=getValueOfLocationId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getAdditionalLoad())
            {
                ret[pMasqueradingVector[4]]=getValueOfAdditionalLoad();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrivialImpactId())
    {
        ret["trivial_impact_id"]=getValueOfTrivialImpactId();
    }
    else
    {
        ret["trivial_impact_id"]=Json::Value();
    }
    if(getTimeStamp())
    {
        ret["time_stamp"]=getTimeStamp()->toDbStringLocal();
    }
    else
    {
        ret["time_stamp"]=Json::Value();
    }
    if(getLocationId())
    {
        ret["location_id"]=getValueOfLocationId();
    }
    else
    {
        ret["location_id"]=Json::Value();
    }
    if(getAdditionalLoad())
    {
        ret["additional_load"]=getValueOfAdditionalLoad();
    }
    else
    {
        ret["additional_load"]=Json::Value();
    }
    return ret;
}

bool TrivialJobs::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("trivial_impact_id"))
    {
        if(!validJsonOfField(1, "trivial_impact_id", pJson["trivial_impact_id"], err, true))
            return false;
    }
    else
    {
        err="The trivial_impact_id column cannot be null";
        return false;
    }
    if(pJson.isMember("time_stamp"))
    {
        if(!validJsonOfField(2, "time_stamp", pJson["time_stamp"], err, true))
            return false;
    }
    else
    {
        err="The time_stamp column cannot be null";
        return false;
    }
    if(pJson.isMember("location_id"))
    {
        if(!validJsonOfField(3, "location_id", pJson["location_id"], err, true))
            return false;
    }
    if(pJson.isMember("additional_load"))
    {
        if(!validJsonOfField(4, "additional_load", pJson["additional_load"], err, true))
            return false;
    }
    return true;
}
bool TrivialJobs::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TrivialJobs::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("trivial_impact_id"))
    {
        if(!validJsonOfField(1, "trivial_impact_id", pJson["trivial_impact_id"], err, false))
            return false;
    }
    if(pJson.isMember("time_stamp"))
    {
        if(!validJsonOfField(2, "time_stamp", pJson["time_stamp"], err, false))
            return false;
    }
    if(pJson.isMember("location_id"))
    {
        if(!validJsonOfField(3, "location_id", pJson["location_id"], err, false))
            return false;
    }
    if(pJson.isMember("additional_load"))
    {
        if(!validJsonOfField(4, "additional_load", pJson["additional_load"], err, false))
            return false;
    }
    return true;
}
bool TrivialJobs::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TrivialJobs::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
