/**
 *
 *  TrivialJobs.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon {
namespace orm {
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model {
namespace calendar_db {

class TrivialJobs {
  public:
    struct Cols {
        static const std::string _id;
        static const std::string _trivial_impact_id;
        static const std::string _time_stamp;
        static const std::string _location_id;
        static const std::string _additional_load;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column
     * names, otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select
     * all columns by an asterisk), please set the offset to -1.
     */
    explicit TrivialJobs(const drogon::orm::Row &r,
                         const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit TrivialJobs(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    TrivialJobs(
        const Json::Value &pJson,
        const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    TrivialJobs() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(
        const Json::Value &pJson,
        const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson,
                                        std::string &err);
    static bool validateMasqueradedJsonForCreation(
        const Json::Value &,
        const std::vector<std::string> &pMasqueradingVector, std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson,
                                      std::string &err);
    static bool validateMasqueradedJsonForUpdate(
        const Json::Value &,
        const std::vector<std::string> &pMasqueradingVector, std::string &err);
    static bool validJsonOfField(size_t index, const std::string &fieldName,
                                 const Json::Value &pJson, std::string &err,
                                 bool isForCreation);

    /**  For column id  */
    /// Get the value of the column id, returns the default value if the column
    /// is null
    const int32_t &getValueOfId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an
    /// empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    /// Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column trivial_impact_id  */
    /// Get the value of the column trivial_impact_id, returns the default value
    /// if the column is null
    const int32_t &getValueOfTrivialImpactId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an
    /// empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getTrivialImpactId() const noexcept;
    /// Set the value of the column trivial_impact_id
    void setTrivialImpactId(const int32_t &pTrivialImpactId) noexcept;

    /**  For column time_stamp  */
    /// Get the value of the column time_stamp, returns the default value if the
    /// column is null
    const ::trantor::Date &getValueOfTimeStamp() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an
    /// empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getTimeStamp() const noexcept;
    /// Set the value of the column time_stamp
    void setTimeStamp(const ::trantor::Date &pTimeStamp) noexcept;

    /**  For column location_id  */
    /// Get the value of the column location_id, returns the default value if
    /// the column is null
    const std::string &getValueOfLocationId() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an
    /// empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLocationId() const noexcept;
    /// Set the value of the column location_id
    void setLocationId(const std::string &pLocationId) noexcept;
    void setLocationId(std::string &&pLocationId) noexcept;
    void setLocationIdToNull() noexcept;

    /**  For column additional_load  */
    /// Get the value of the column additional_load, returns the default value
    /// if the column is null
    const double &getValueOfAdditionalLoad() const noexcept;
    /// Return a shared_ptr object pointing to the column const value, or an
    /// empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getAdditionalLoad() const noexcept;
    /// Set the value of the column additional_load
    void setAdditionalLoad(const double &pAdditionalLoad) noexcept;
    void setAdditionalLoadToNull() noexcept;

    static size_t getColumnNumber() noexcept { return 5; }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(
        const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<TrivialJobs>;
    friend drogon::orm::BaseBuilder<TrivialJobs, true, true>;
    friend drogon::orm::BaseBuilder<TrivialJobs, true, false>;
    friend drogon::orm::BaseBuilder<TrivialJobs, false, true>;
    friend drogon::orm::BaseBuilder<TrivialJobs, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<TrivialJobs>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    /// For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<int32_t> trivialImpactId_;
    std::shared_ptr<::trantor::Date> timeStamp_;
    std::shared_ptr<std::string> locationId_;
    std::shared_ptr<double> additionalLoad_;
    struct MetaData {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[5] = {false};

  public:
    static const std::string &sqlForFindingByPrimaryKey() {
        static const std::string sql =
            "select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey() {
        static const std::string sql =
            "delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const {
        std::string sql = "insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if (dirtyFlag_[1]) {
            sql += "trivial_impact_id,";
            ++parametersCount;
        }
        if (dirtyFlag_[2]) {
            sql += "time_stamp,";
            ++parametersCount;
        }
        if (dirtyFlag_[3]) {
            sql += "location_id,";
            ++parametersCount;
        }
        if (dirtyFlag_[4]) {
            sql += "additional_load,";
            ++parametersCount;
        }
        needSelection = true;
        if (parametersCount > 0) {
            sql[sql.length() - 1] = ')';
            sql += " values (";
        } else
            sql += ") values (";

        int placeholder = 1;
        char placeholderStr[64];
        size_t n = 0;
        sql += "default,";
        if (dirtyFlag_[1]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,",
                         placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[2]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,",
                         placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[3]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,",
                         placeholder++);
            sql.append(placeholderStr, n);
        }
        if (dirtyFlag_[4]) {
            n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,",
                         placeholder++);
            sql.append(placeholderStr, n);
        }
        if (parametersCount > 0) {
            sql.resize(sql.length() - 1);
        }
        if (needSelection) {
            sql.append(") returning *");
        } else {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace calendar_db
} // namespace drogon_model
